# -*- coding: utf-8 -*-
"""Aplikasi Keuangan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-mCaF22n1vEddFTypoHWkhbXxnRwgJY
"""

import streamlit as st

class PengelolaanKeuangan:
    def __init__(self):
        self.transaksi = []

    def tambah_pemasukan(self, jumlah, keterangan):
        self.transaksi.append({"jenis": "pemasukan", "jumlah": jumlah, "keterangan": keterangan})

    def tambah_pengeluaran(self, jumlah, keterangan):
        self.transaksi.append({"jenis": "pengeluaran", "jumlah": jumlah, "keterangan": keterangan})

    def tampilkan_saldo(self):
        saldo = sum(t["jumlah"] if t["jenis"] == "pemasukan" else -t["jumlah"] for t in self.transaksi)
        return saldo

    def tampilkan_transaksi(self):
        return self.transaksi

def main():
    st.title("Aplikasi Pengelolaan Keuangan")

    keuangan = PengelolaanKeuangan()

    menu = ["Tambah Pemasukan", "Tambah Pengeluaran", "Tampilkan Saldo", "Tampilkan Transaksi"]
    pilihan = st.sidebar.selectbox("Menu", menu)

    if pilihan == "Tambah Pemasukan":
        st.subheader("Tambah Pemasukan")
        jumlah = st.number_input("Jumlah pemasukan", min_value=0, value=0)
        keterangan = st.text_input("Keterangan")
        if st.button("Tambah"):
            keuangan.tambah_pemasukan(jumlah, keterangan)
            st.success(f"Pemasukan sebesar Rp {jumlah} telah ditambahkan.")

    elif pilihan == "Tambah Pengeluaran":
        st.subheader("Tambah Pengeluaran")
        jumlah = st.number_input("Jumlah pengeluaran", min_value=0, value=0)
        keterangan = st.text_input("Keterangan")
        if st.button("Tambah"):
            keuangan.tambah_pengeluaran(jumlah, keterangan)
            st.success(f"Pengeluaran sebesar Rp {jumlah} telah ditambahkan.")

    elif pilihan == "Tampilkan Saldo":
        st.subheader("Saldo Saat Ini")
        saldo = keuangan.tampilkan_saldo()
        st.info(f"Saldo saat ini: Rp {saldo}")

    elif pilihan == "Tampilkan Transaksi":
        st.subheader("Semua Transaksi")
        transaksi = keuangan.tampilkan_transaksi()
        for t in transaksi:
            st.write(f"{t['jenis'].capitalize()}: Rp {t['jumlah']} ({t['keterangan']})")

if __name__ == "__main__":
    main()