# -*- coding: utf-8 -*-
"""Program Keuangan Produk .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ghtv_hili4-p3maamktvLncHIZmJL1dW
"""

import json

# Fungsi untuk menghitung total biaya, total pendapatan, dan keuntungan
def hitung_keuangan(biaya_produksi, harga_jual, jumlah_unit):
    total_biaya = biaya_produksi * jumlah_unit
    total_pendapatan = harga_jual * jumlah_unit
    keuntungan = total_pendapatan - total_biaya

    return total_biaya, total_pendapatan, keuntungan

# Fungsi untuk menyimpan hasil perhitungan ke file JSON
def simpan_keuangan(nama_barang, biaya_produksi, harga_jual, jumlah_unit, total_biaya, total_pendapatan, keuntungan):
    data = {
        "Nama Barang": nama_barang,
        "Biaya Produksi": biaya_produksi,
        "Harga Jual": harga_jual,
        "Jumlah Unit": jumlah_unit,
        "Total Biaya": total_biaya,
        "Total Pendapatan": total_pendapatan,
        "Keuntungan": keuntungan
    }

    with open('data_keuangan.json', 'a') as file:
        json.dump(data, file)
        file.write('\n')

# Fungsi untuk membaca dan menampilkan hasil perhitungan dari file JSON
def tampilkan_hasil():
    try:
        with open('data_keuangan.json', 'r') as file:
            print("\n--- Hasil Perhitungan Tersimpan ---")
            for line in file:
                data = json.loads(line.strip())
                print(f"\nNama Barang: {data['Nama Barang']}")
                print(f"Biaya Produksi: Rp{data['Biaya Produksi']:,.2f}")
                print(f"Harga Jual: Rp{data['Harga Jual']:,.2f}")
                print(f"Jumlah Unit: {data['Jumlah Unit']}")
                print(f"Total Biaya: Rp{data['Total Biaya']:,.2f}")
                print(f"Total Pendapatan: Rp{data['Total Pendapatan']:,.2f}")
                print(f"Keuntungan: Rp{data['Keuntungan']:,.2f}")

    except FileNotFoundError:
        print("Tidak ada hasil perhitungan yang tersimpan.")

# Fungsi utama untuk menampilkan menu
def main():
    while True:
        print("\n--- Menu ---")
        print("1. Hitung keuangan")
        print("2. Tampilkan hasil perhitungan tersimpan")
        print("3. Keluar")
        pilihan = input("Pilih opsi: ")

        if pilihan == '1':
            try:
                nama_barang = input("Masukkan nama barang: ")
                biaya_produksi = float(input("Masukkan biaya produksi per unit: "))
                harga_jual = float(input("Masukkan harga jual per unit: "))
                jumlah_unit = int(input("Masukkan jumlah unit yang diproduksi: "))

                total_biaya, total_pendapatan, keuntungan = hitung_keuangan(biaya_produksi, harga_jual, jumlah_unit)

                print("\n--- Hasil Perhitungan ---")
                print(f"Nama Barang: {nama_barang}")
                print(f"Total Biaya: Rp{total_biaya:,.2f}")
                print(f"Total Pendapatan: Rp{total_pendapatan:,.2f}")
                print(f"Keuntungan: Rp{keuntungan:,.2f}")

                simpan_keuangan(nama_barang, biaya_produksi, harga_jual, jumlah_unit, total_biaya, total_pendapatan, keuntungan)

                print("\nHasil perhitungan telah disimpan di 'data_keuangan.json'.")

            except ValueError:
                print("Input tidak valid. Harap masukkan angka yang benar.")
        elif pilihan == '2':
            tampilkan_hasil()
        elif pilihan == '3':
            break
        else:
            print("Pilihan tidak valid. Harap pilih opsi yang tersedia.")

if __name__ == "__main__":
    print("Selamat datang di Program Keuangan Produk")

# Memanggil fungsi utama untuk menjalankan program
    main()